"""Derive config/profile.yaml from a resume PDF.

Scoring needs to know which technologies actually appear on the resume so that
overlap with a job description is measurable. Rather than hardcode that list, this
walks a taxonomy of data/AI tooling and records which terms the resume mentions,
bucketing them by how much signal a match carries.

    python scripts/build_profile.py --resume "path/to/resume.pdf"

The ``adjacent`` group is included regardless of the resume: a posting asking for
Snowflake or BigQuery is still an excellent fit for someone with Redshift and
Databricks depth, and refusing to score those would throw away good matches.
"""

from __future__ import annotations

import argparse
import datetime
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]

# term-pool name -> (group weight, candidate terms)
TAXONOMY: dict[str, tuple[float, list[str]]] = {
    "core_data": (3.0, [
        "dbt", "Airflow", "Kafka", "Spark", "PySpark", "Databricks", "Redshift",
        "Snowflake", "BigQuery", "Flink", "Dagster", "Prefect", "Beam", "Hadoop",
        "Hive", "Presto", "Trino", "Iceberg", "Delta Lake", "Parquet",
    ]),
    "ai_ml": (2.5, [
        "PyTorch", "TensorFlow", "LangChain", "pgvector", "LLM", "embedding",
        "embeddings", "RAG", "vector database", "scikit-learn", "Hugging Face",
        "transformer", "fine-tuning", "OpenCV", "NLP", "semantic search",
        "machine learning", "deep learning", "MLOps", "feature store",
    ]),
    "platform": (2.0, [
        "AWS", "Azure", "GCP", "Google Cloud", "Docker", "Kubernetes", "Terraform",
        "CI/CD", "Jenkins", "GitHub Actions", "Lambda", "S3", "EKS", "Databricks",
        "microservices", "REST API", "gRPC",
    ]),
    "storage": (2.0, [
        "PostgreSQL", "Postgres", "MySQL", "Aurora", "DynamoDB", "MongoDB",
        "Cassandra", "Redis", "ClickHouse", "Elasticsearch", "data warehouse",
        "data lake", "lakehouse", "OLAP",
    ]),
    "bi": (1.5, [
        "Power BI", "Tableau", "Looker", "Mode", "Sigma", "Superset", "Metabase",
        "Hex", "dashboard", "visualization",
    ]),
    "foundational": (1.0, [
        "Python", "SQL", "Java", "JavaScript", "TypeScript", "Scala", "\\bR\\b",
        "Git", "Linux", "Bash", "Pandas", "NumPy",
    ]),
    "practice": (1.5, [
        "ETL", "ELT", "data pipeline", "data modeling", "dimensional modeling",
        "streaming", "batch processing", "orchestration", "data quality",
        "data governance", "star schema", "incremental", "partitioning",
        "A/B testing", "experimentation", "analytics", "SLA",
    ]),
}

# Scored even when absent from the resume - near-neighbour tooling.
ADJACENT = (1.5, [
    "Snowflake", "BigQuery", "Looker", "Tableau", "Fivetran", "Airbyte",
    "Dagster", "Prefect", "Segment", "Amplitude", "Mixpanel", "Terraform",
    "Iceberg", "Trino", "dbt Cloud", "Great Expectations", "Monte Carlo",
])


def extract_text(path: Path) -> str:
    try:
        from pypdf import PdfReader
    except ImportError:  # pragma: no cover
        raise SystemExit("pip install pypdf")

    if path.suffix.lower() != ".pdf":
        return path.read_text(encoding="utf-8", errors="ignore")
    reader = PdfReader(str(path))
    return "\n".join(page.extract_text() or "" for page in reader.pages)


def detect(text: str, terms: list[str]) -> list[str]:
    found = []
    for term in terms:
        pattern = term if term.startswith("\\b") else r"\b" + re.escape(term) + r"\b"
        if re.search(pattern, text, re.I):
            found.append(term.replace("\\b", ""))
    return found


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--resume", required=True)
    parser.add_argument("--out", default=str(REPO / "config" / "profile.yaml"))
    # Raised from 18: at that level a posting mentioning Python, SQL and one tool
    # already maxed the skill points, so a deep stack match looked identical to a
    # shallow one. At 20, near-saturation needs most of the core data stack.
    parser.add_argument("--skill-target", type=float, default=20.0)
    args = parser.parse_args()

    resume_path = Path(args.resume)
    if not resume_path.exists():
        raise SystemExit(f"Resume not found: {resume_path}")

    text = extract_text(resume_path)
    if not text.strip():
        raise SystemExit("Could not extract any text from the resume")

    lines = [
        "# Generated by scripts/build_profile.py from a resume.",
        "# Regenerate whenever the resume changes; hand-tuning below is preserved",
        "# only if you re-apply it, so keep edits small and deliberate.",
        # Deliberately not the source filename: resumes are usually named after their
        # author, and this file is committed. A date says when it was last refreshed
        # without naming anyone.
        f"# Generated: {datetime.date.today().isoformat()}",
        "",
        f"skill_target: {args.skill_target}",
        "",
        "skills:",
    ]

    total_terms = 0
    summary: list[str] = []
    for group, (weight, pool) in TAXONOMY.items():
        found = detect(text, pool)
        if not found:
            continue
        total_terms += len(found)
        summary.append(f"  {group:<14} w={weight}  {len(found):>2} terms: {', '.join(found)}")
        lines.append(f"  {group}:")
        lines.append(f"    weight: {weight}")
        lines.append("    terms:")
        lines.extend(f"      - {t}" for t in found)
        lines.append("")

    weight, adj_terms = ADJACENT
    lines.append("  # Near-neighbour tooling: not on the resume, but a posting that")
    lines.append("  # asks for these is still a strong fit given the core stack.")
    lines.append("  adjacent:")
    lines.append(f"    weight: {weight}")
    lines.append("    terms:")
    lines.extend(f"      - {t}" for t in adj_terms)
    lines.append("")

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")

    print(f"Extracted {len(text)} chars from {resume_path.name}")
    print(f"Detected {total_terms} resume terms across {len(summary)} groups:\n")
    print("\n".join(summary))
    print(f"\nWrote {out}")


if __name__ == "__main__":
    main()
